[project]
name = "todo-manager"
version = "0.1.0"
description = "A simple CLI to-do manager with some AI capabilities and a built-in timer."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "inquirerpy>=0.3.4",
    "ollama>=0.6.1",
    "playsound3>=3.3.1",
    "prettytable>=3.17.0",
    "textual>=7.5.0",
]
